# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_2_2.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 786)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_load_train_array = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load_train_array.setGeometry(QtCore.QRect(270, 70, 171, 31))
        self.btn_load_train_array.setObjectName("btn_load_train_array")
        self.btn_start_training = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_training.setGeometry(QtCore.QRect(10, 160, 131, 31))
        self.btn_start_training.setObjectName("btn_start_training")
        self.cvl_test_2 = QtWidgets.QLabel(self.centralwidget)
        self.cvl_test_2.setGeometry(QtCore.QRect(530, 100, 128, 128))
        self.cvl_test_2.setText("")
        self.cvl_test_2.setObjectName("cvl_test_2")
        self.line_folder = QtWidgets.QLineEdit(self.centralwidget)
        self.line_folder.setGeometry(QtCore.QRect(10, 80, 171, 21))
        self.line_folder.setObjectName("line_folder")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 80, 81, 21))
        self.label_3.setObjectName("label_3")
        self.spin_iterations = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_iterations.setGeometry(QtCore.QRect(80, 110, 51, 22))
        self.spin_iterations.setMinimum(1)
        self.spin_iterations.setMaximum(1000)
        self.spin_iterations.setProperty("value", 20)
        self.spin_iterations.setObjectName("spin_iterations")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_5.setObjectName("label_5")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(140, 110, 301, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.ocl_test_array = QtWidgets.QLabel(self.centralwidget)
        self.ocl_test_array.setGeometry(QtCore.QRect(30, 310, 256, 256))
        self.ocl_test_array.setText("")
        self.ocl_test_array.setObjectName("ocl_test_array")
        self.ocl_test_image = QtWidgets.QLabel(self.centralwidget)
        self.ocl_test_image.setGeometry(QtCore.QRect(300, 400, 128, 128))
        self.ocl_test_image.setText("")
        self.ocl_test_image.setObjectName("ocl_test_image")
        self.spin_test_array_id = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_test_array_id.setGeometry(QtCore.QRect(200, 280, 42, 21))
        self.spin_test_array_id.setMinimum(1)
        self.spin_test_array_id.setMaximum(4)
        self.spin_test_array_id.setObjectName("spin_test_array_id")
        self.btn_load_test_array = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load_test_array.setGeometry(QtCore.QRect(20, 270, 171, 31))
        self.btn_load_test_array.setObjectName("btn_load_test_array")
        self.btn_predict = QtWidgets.QPushButton(self.centralwidget)
        self.btn_predict.setGeometry(QtCore.QRect(20, 620, 171, 31))
        self.btn_predict.setObjectName("btn_predict")
        self.label_predicted = QtWidgets.QLabel(self.centralwidget)
        self.label_predicted.setGeometry(QtCore.QRect(30, 660, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_predicted.setFont(font)
        self.label_predicted.setAlignment(QtCore.Qt.AlignCenter)
        self.label_predicted.setObjectName("label_predicted")
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setGeometry(QtCore.QRect(310, 570, 16, 111))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_3.setGeometry(QtCore.QRect(340, 570, 16, 111))
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_4 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_4.setGeometry(QtCore.QRect(370, 570, 16, 111))
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_4.setObjectName("progressBar_4")
        self.progressBar_5 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_5.setGeometry(QtCore.QRect(400, 570, 16, 111))
        self.progressBar_5.setProperty("value", 0)
        self.progressBar_5.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_5.setObjectName("progressBar_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(310, 680, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 200, 450, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 220, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(340, 680, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(370, 680, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(400, 680, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.btn_save_to_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_to_file.setGeometry(QtCore.QRect(160, 160, 131, 31))
        self.btn_save_to_file.setObjectName("btn_save_to_file")
        self.btn_load_from_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load_from_file.setGeometry(QtCore.QRect(310, 160, 131, 31))
        self.btn_load_from_file.setObjectName("btn_load_from_file")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LR2"))
        self.btn_load_train_array.setText(_translate("MainWindow", "Load train array"))
        self.btn_start_training.setText(_translate("MainWindow", "Train"))
        self.line_folder.setText(_translate("MainWindow", "LR2_data/"))
        self.label.setText(_translate("MainWindow", "Network trainer"))
        self.label_2.setText(_translate("MainWindow", "Files folder:"))
        self.label_3.setText(_translate("MainWindow", "{0 - 3}.bmp"))
        self.label_5.setText(_translate("MainWindow", "Iterations: "))
        self.btn_load_test_array.setText(_translate("MainWindow", "Load test array"))
        self.btn_predict.setText(_translate("MainWindow", "Load and predict"))
        self.label_predicted.setText(_translate("MainWindow", "EMPTY"))
        self.label_6.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "Network tester"))
        self.label_7.setText(_translate("MainWindow", "2"))
        self.label_8.setText(_translate("MainWindow", "3"))
        self.label_9.setText(_translate("MainWindow", "4"))
        self.btn_save_to_file.setText(_translate("MainWindow", "Save to file"))
        self.btn_load_from_file.setText(_translate("MainWindow", "Load from file"))

