# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_6.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 870)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 50, 751, 461))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(340, 30, 401, 131))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.test_image = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.test_image.setObjectName("test_image")
        self.gridLayout_4.addWidget(self.test_image, 0, 1, 1, 1)
        self.btn_single = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_single.setObjectName("btn_single")
        self.gridLayout_4.addWidget(self.btn_single, 1, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btn_camera_stop = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_camera_stop.setObjectName("btn_camera_stop")
        self.gridLayout_5.addWidget(self.btn_camera_stop, 0, 3, 1, 1)
        self.camera_id = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.camera_id.setObjectName("camera_id")
        self.gridLayout_5.addWidget(self.camera_id, 0, 0, 1, 1)
        self.btn_camera_start = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_camera_start.setObjectName("btn_camera_start")
        self.gridLayout_5.addWidget(self.btn_camera_start, 0, 1, 1, 1)
        self.btn_camera_pause = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_camera_pause.setEnabled(False)
        self.btn_camera_pause.setObjectName("btn_camera_pause")
        self.gridLayout_5.addWidget(self.btn_camera_pause, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 1, 1)
        self.checkbox_binarize = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkbox_binarize.setChecked(True)
        self.checkbox_binarize.setObjectName("checkbox_binarize")
        self.gridLayout_4.addWidget(self.checkbox_binarize, 3, 1, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 30, 301, 131))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 0, 0, 1, 1)
        self.btn_load_model = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn_load_model.setObjectName("btn_load_model")
        self.gridLayout_6.addWidget(self.btn_load_model, 2, 1, 1, 1)
        self.model_file = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.model_file.setObjectName("model_file")
        self.gridLayout_6.addWidget(self.model_file, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.model_width = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.model_width.setMinimum(1)
        self.model_width.setMaximum(9999)
        self.model_width.setProperty("value", 160)
        self.model_width.setObjectName("model_width")
        self.horizontalLayout.addWidget(self.model_width)
        self.model_height = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.model_height.setMinimum(1)
        self.model_height.setMaximum(9999)
        self.model_height.setProperty("value", 120)
        self.model_height.setObjectName("model_height")
        self.horizontalLayout.addWidget(self.model_height)
        self.gridLayout_6.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 180, 322, 267))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.main_image = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.main_image.setMinimumSize(QtCore.QSize(320, 240))
        self.main_image.setMaximumSize(QtCore.QSize(320, 240))
        self.main_image.setText("")
        self.main_image.setObjectName("main_image")
        self.verticalLayout.addWidget(self.main_image)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(380, 180, 322, 267))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.mask_image = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.mask_image.setMinimumSize(QtCore.QSize(320, 240))
        self.mask_image.setMaximumSize(QtCore.QSize(320, 240))
        self.mask_image.setText("")
        self.mask_image.setObjectName("mask_image")
        self.verticalLayout_2.addWidget(self.mask_image)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(190, 520, 421, 301))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 401, 250))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cnn_masks_folder = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.cnn_masks_folder.setObjectName("cnn_masks_folder")
        self.gridLayout_3.addWidget(self.cnn_masks_folder, 2, 1, 1, 1)
        self.cnn_train_save_file = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.cnn_train_save_file.setObjectName("cnn_train_save_file")
        self.gridLayout_3.addWidget(self.cnn_train_save_file, 9, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_train_start = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_train_start.setObjectName("btn_train_start")
        self.horizontalLayout_2.addWidget(self.btn_train_start)
        self.btn_train_save = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_train_save.setObjectName("btn_train_save")
        self.horizontalLayout_2.addWidget(self.btn_train_save)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 8, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 6, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cnn_model_width = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.cnn_model_width.setMinimum(1)
        self.cnn_model_width.setMaximum(9999)
        self.cnn_model_width.setProperty("value", 160)
        self.cnn_model_width.setObjectName("cnn_model_width")
        self.horizontalLayout_4.addWidget(self.cnn_model_width)
        self.cnn_model_height = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.cnn_model_height.setMinimum(1)
        self.cnn_model_height.setMaximum(9999)
        self.cnn_model_height.setProperty("value", 120)
        self.cnn_model_height.setObjectName("cnn_model_height")
        self.horizontalLayout_4.addWidget(self.cnn_model_height)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 9, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 1)
        self.cnn_images_folder = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.cnn_images_folder.setObjectName("cnn_images_folder")
        self.gridLayout_3.addWidget(self.cnn_images_folder, 1, 1, 1, 1)
        self.cnn_epochs = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.cnn_epochs.setMinimum(1)
        self.cnn_epochs.setMaximum(9999)
        self.cnn_epochs.setProperty("value", 20)
        self.cnn_epochs.setObjectName("cnn_epochs")
        self.gridLayout_3.addWidget(self.cnn_epochs, 4, 1, 1, 1)
        self.cnn_train_folder = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.cnn_train_folder.setObjectName("cnn_train_folder")
        self.gridLayout_3.addWidget(self.cnn_train_folder, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 5, 0, 1, 1)
        self.cnn_steps_per_epoch = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.cnn_steps_per_epoch.setMinimum(1)
        self.cnn_steps_per_epoch.setMaximum(9999)
        self.cnn_steps_per_epoch.setProperty("value", 2000)
        self.cnn_steps_per_epoch.setObjectName("cnn_steps_per_epoch")
        self.gridLayout_3.addWidget(self.cnn_steps_per_epoch, 5, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LR6 U-Net"))
        self.label.setText(_translate("MainWindow", "U-Net CNN"))
        self.groupBox_4.setTitle(_translate("MainWindow", "U-Net"))
        self.label_19.setText(_translate("MainWindow", "Single image Folder:"))
        self.label_3.setText(_translate("MainWindow", "Camera:"))
        self.test_image.setText(_translate("MainWindow", "LR6_data\\test"))
        self.btn_single.setText(_translate("MainWindow", "Proceed random image"))
        self.btn_camera_stop.setText(_translate("MainWindow", "Stop"))
        self.btn_camera_start.setText(_translate("MainWindow", "Start"))
        self.btn_camera_pause.setText(_translate("MainWindow", "Pause"))
        self.label_8.setText(_translate("MainWindow", "Binarize mask:"))
        self.checkbox_binarize.setText(_translate("MainWindow", "Enable binarization"))
        self.label_20.setText(_translate("MainWindow", "Model file:"))
        self.btn_load_model.setText(_translate("MainWindow", "Load model"))
        self.model_file.setText(_translate("MainWindow", "LR6_data\\model.h5"))
        self.label_2.setText(_translate("MainWindow", "Model Resolution:"))
        self.label_7.setText(_translate("MainWindow", "Original Image:"))
        self.label_9.setText(_translate("MainWindow", "Predicted mask:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Model trainer"))
        self.cnn_masks_folder.setText(_translate("MainWindow", "train_masks"))
        self.cnn_train_save_file.setText(_translate("MainWindow", "LR6_data\\model.h5"))
        self.btn_train_start.setText(_translate("MainWindow", "Train"))
        self.btn_train_save.setText(_translate("MainWindow", "Save to file"))
        self.label_21.setText(_translate("MainWindow", "Masks folder:"))
        self.label_4.setText(_translate("MainWindow", "Model Resolution:"))
        self.label_5.setText(_translate("MainWindow", "Epochs:"))
        self.label_16.setText(_translate("MainWindow", "Save file:"))
        self.label_15.setText(_translate("MainWindow", "Images folder:"))
        self.cnn_images_folder.setText(_translate("MainWindow", "train_images"))
        self.cnn_train_folder.setText(_translate("MainWindow", "LR6_data\\train"))
        self.label_17.setText(_translate("MainWindow", "Train folder:"))
        self.label_6.setText(_translate("MainWindow", "Steps per epoch:"))

