# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_4.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 774)
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_camera_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_camera_start.setGeometry(QtCore.QRect(60, 40, 81, 31))
        self.btn_camera_start.setObjectName("btn_camera_start")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(270, 0, 21, 740))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 100, 271, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.cvl_image = QtWidgets.QLabel(self.centralwidget)
        self.cvl_image.setGeometry(QtCore.QRect(290, 120, 640, 480))
        self.cvl_image.setText("")
        self.cvl_image.setObjectName("cvl_image")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 310, 161, 21))
        self.label_5.setObjectName("label_5")
        self.slider_contrast = QtWidgets.QSlider(self.centralwidget)
        self.slider_contrast.setGeometry(QtCore.QRect(10, 340, 251, 21))
        self.slider_contrast.setMinimum(0)
        self.slider_contrast.setMaximum(100)
        self.slider_contrast.setProperty("value", 50)
        self.slider_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.slider_contrast.setObjectName("slider_contrast")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 250, 161, 21))
        self.label_6.setObjectName("label_6")
        self.slider_brightness = QtWidgets.QSlider(self.centralwidget)
        self.slider_brightness.setGeometry(QtCore.QRect(10, 280, 251, 21))
        self.slider_brightness.setMinimum(0)
        self.slider_brightness.setMaximum(100)
        self.slider_brightness.setPageStep(10)
        self.slider_brightness.setProperty("value", 50)
        self.slider_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.slider_brightness.setObjectName("slider_brightness")
        self.camera_id = QtWidgets.QSpinBox(self.centralwidget)
        self.camera_id.setGeometry(QtCore.QRect(10, 40, 41, 31))
        self.camera_id.setMinimum(0)
        self.camera_id.setMaximum(1024)
        self.camera_id.setProperty("value", 0)
        self.camera_id.setObjectName("camera_id")
        self.btn_camera_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_camera_stop.setGeometry(QtCore.QRect(140, 40, 81, 31))
        self.btn_camera_stop.setObjectName("btn_camera_stop")
        self.check_dshow = QtWidgets.QCheckBox(self.centralwidget)
        self.check_dshow.setGeometry(QtCore.QRect(10, 80, 101, 17))
        self.check_dshow.setChecked(True)
        self.check_dshow.setObjectName("check_dshow")
        self.group_current_image = QtWidgets.QGroupBox(self.centralwidget)
        self.group_current_image.setGeometry(QtCore.QRect(10, 450, 161, 81))
        self.group_current_image.setObjectName("group_current_image")
        self.btn_save_current = QtWidgets.QPushButton(self.group_current_image)
        self.btn_save_current.setGeometry(QtCore.QRect(30, 40, 91, 31))
        self.btn_save_current.setObjectName("btn_save_current")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 540, 231, 191))
        self.groupBox.setObjectName("groupBox")
        self.btn_start_multiple = QtWidgets.QPushButton(self.groupBox)
        self.btn_start_multiple.setGeometry(QtCore.QRect(30, 150, 91, 31))
        self.btn_start_multiple.setObjectName("btn_start_multiple")
        self.btn_stop_multiple = QtWidgets.QPushButton(self.groupBox)
        self.btn_stop_multiple.setGeometry(QtCore.QRect(130, 150, 91, 31))
        self.btn_stop_multiple.setObjectName("btn_stop_multiple")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(40, 90, 91, 16))
        self.label_9.setObjectName("label_9")
        self.spin_interval = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spin_interval.setGeometry(QtCore.QRect(150, 90, 62, 22))
        self.spin_interval.setMaximum(9999.99)
        self.spin_interval.setProperty("value", 1.0)
        self.spin_interval.setObjectName("spin_interval")
        self.radio_infinite = QtWidgets.QRadioButton(self.groupBox)
        self.radio_infinite.setGeometry(QtCore.QRect(40, 30, 121, 17))
        self.radio_infinite.setObjectName("radio_infinite")
        self.radio_limit = QtWidgets.QRadioButton(self.groupBox)
        self.radio_limit.setGeometry(QtCore.QRect(40, 60, 101, 17))
        self.radio_limit.setChecked(True)
        self.radio_limit.setObjectName("radio_limit")
        self.spin_limit = QtWidgets.QSpinBox(self.groupBox)
        self.spin_limit.setGeometry(QtCore.QRect(150, 60, 61, 22))
        self.spin_limit.setMinimum(10)
        self.spin_limit.setMaximum(9999)
        self.spin_limit.setObjectName("spin_limit")
        self.label_saved_files = QtWidgets.QLabel(self.groupBox)
        self.label_saved_files.setGeometry(QtCore.QRect(50, 120, 121, 16))
        self.label_saved_files.setObjectName("label_saved_files")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 370, 261, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.line_file = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_file.setGeometry(QtCore.QRect(10, 39, 161, 21))
        self.line_file.setObjectName("line_file")
        self.btn_browse = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_browse.setGeometry(QtCore.QRect(170, 30, 81, 31))
        self.btn_browse.setObjectName("btn_browse")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 120, 120, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radio_color_hsv = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_color_hsv.setGeometry(QtCore.QRect(10, 60, 91, 17))
        self.radio_color_hsv.setObjectName("radio_color_hsv")
        self.radio_color_grayscale = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_color_grayscale.setGeometry(QtCore.QRect(10, 90, 91, 17))
        self.radio_color_grayscale.setObjectName("radio_color_grayscale")
        self.radio_color_rgb = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_color_rgb.setGeometry(QtCore.QRect(10, 30, 61, 17))
        self.radio_color_rgb.setChecked(True)
        self.radio_color_rgb.setObjectName("radio_color_rgb")
        self.cvl_image.raise_()
        self.btn_camera_start.raise_()
        self.label.raise_()
        self.line_2.raise_()
        self.line.raise_()
        self.label_5.raise_()
        self.slider_contrast.raise_()
        self.label_6.raise_()
        self.slider_brightness.raise_()
        self.camera_id.raise_()
        self.btn_camera_stop.raise_()
        self.check_dshow.raise_()
        self.group_current_image.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LR4 Camera collector"))
        self.btn_camera_start.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Camera:"))
        self.label_5.setText(_translate("MainWindow", "Contrast:"))
        self.label_6.setText(_translate("MainWindow", "Brightness:"))
        self.btn_camera_stop.setText(_translate("MainWindow", "Stop"))
        self.check_dshow.setText(_translate("MainWindow", "DSHOW"))
        self.group_current_image.setTitle(_translate("MainWindow", "Single capture"))
        self.btn_save_current.setText(_translate("MainWindow", "Save"))
        self.groupBox.setTitle(_translate("MainWindow", "Multiple capture"))
        self.btn_start_multiple.setText(_translate("MainWindow", "Start"))
        self.btn_stop_multiple.setText(_translate("MainWindow", "Stop"))
        self.label_9.setText(_translate("MainWindow", "Interval (sec):"))
        self.radio_infinite.setText(_translate("MainWindow", "Infinite capture"))
        self.radio_limit.setText(_translate("MainWindow", "Frames limit:"))
        self.label_saved_files.setText(_translate("MainWindow", "Saved 0 files."))
        self.groupBox_2.setTitle(_translate("MainWindow", "1st file name:"))
        self.btn_browse.setText(_translate("MainWindow", "Browse"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Color space"))
        self.radio_color_hsv.setText(_translate("MainWindow", "HSV"))
        self.radio_color_grayscale.setText(_translate("MainWindow", "Grayscale"))
        self.radio_color_rgb.setText(_translate("MainWindow", "RGB"))

