# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_3_Collector.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 639)
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cvl_original = QtWidgets.QLabel(self.centralwidget)
        self.cvl_original.setGeometry(QtCore.QRect(10, 40, 80, 80))
        self.cvl_original.setText("")
        self.cvl_original.setObjectName("cvl_original")
        self.btn_open_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_file.setGeometry(QtCore.QRect(10, 130, 121, 31))
        self.btn_open_file.setObjectName("btn_open_file")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(270, 0, 21, 561))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 170, 271, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.cvl_candidates = QtWidgets.QLabel(self.centralwidget)
        self.cvl_candidates.setGeometry(QtCore.QRect(290, 40, 512, 512))
        self.cvl_candidates.setText("")
        self.cvl_candidates.setObjectName("cvl_candidates")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 190, 161, 21))
        self.label_3.setObjectName("label_3")
        self.btn_candidates_generate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_candidates_generate.setGeometry(QtCore.QRect(40, 520, 191, 31))
        self.btn_candidates_generate.setObjectName("btn_candidates_generate")
        self.spin_cindidates_file = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_cindidates_file.setGeometry(QtCore.QRect(180, 560, 51, 31))
        self.spin_cindidates_file.setObjectName("spin_cindidates_file")
        self.slider_brightness = QtWidgets.QSlider(self.centralwidget)
        self.slider_brightness.setGeometry(QtCore.QRect(10, 300, 251, 21))
        self.slider_brightness.setMinimum(0)
        self.slider_brightness.setMaximum(128)
        self.slider_brightness.setProperty("value", 20)
        self.slider_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.slider_brightness.setObjectName("slider_brightness")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 270, 161, 21))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 330, 161, 21))
        self.label_4.setObjectName("label_4")
        self.slider_shift = QtWidgets.QSlider(self.centralwidget)
        self.slider_shift.setGeometry(QtCore.QRect(10, 360, 251, 21))
        self.slider_shift.setMinimum(0)
        self.slider_shift.setMaximum(2)
        self.slider_shift.setProperty("value", 1)
        self.slider_shift.setOrientation(QtCore.Qt.Horizontal)
        self.slider_shift.setObjectName("slider_shift")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 390, 161, 21))
        self.label_5.setObjectName("label_5")
        self.slider_rotation = QtWidgets.QSlider(self.centralwidget)
        self.slider_rotation.setGeometry(QtCore.QRect(10, 420, 251, 21))
        self.slider_rotation.setMinimum(0)
        self.slider_rotation.setMaximum(15)
        self.slider_rotation.setProperty("value", 9)
        self.slider_rotation.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rotation.setObjectName("slider_rotation")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 450, 161, 21))
        self.label_6.setObjectName("label_6")
        self.slider_noise = QtWidgets.QSlider(self.centralwidget)
        self.slider_noise.setGeometry(QtCore.QRect(10, 480, 251, 21))
        self.slider_noise.setMinimum(0)
        self.slider_noise.setMaximum(128)
        self.slider_noise.setPageStep(10)
        self.slider_noise.setProperty("value", 20)
        self.slider_noise.setOrientation(QtCore.Qt.Horizontal)
        self.slider_noise.setObjectName("slider_noise")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 230, 101, 21))
        self.label_7.setObjectName("label_7")
        self.spin_cindidates_n = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_cindidates_n.setGeometry(QtCore.QRect(110, 220, 51, 31))
        self.spin_cindidates_n.setMinimum(1)
        self.spin_cindidates_n.setMaximum(256)
        self.spin_cindidates_n.setProperty("value", 50)
        self.spin_cindidates_n.setObjectName("spin_cindidates_n")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 560, 101, 21))
        self.label_8.setObjectName("label_8")
        self.cvl_candidates.raise_()
        self.cvl_original.raise_()
        self.btn_open_file.raise_()
        self.label.raise_()
        self.line_2.raise_()
        self.line.raise_()
        self.label_3.raise_()
        self.btn_candidates_generate.raise_()
        self.spin_cindidates_file.raise_()
        self.slider_brightness.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.slider_shift.raise_()
        self.label_5.raise_()
        self.slider_rotation.raise_()
        self.label_6.raise_()
        self.slider_noise.raise_()
        self.label_7.raise_()
        self.spin_cindidates_n.raise_()
        self.label_8.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LR3 Image Generator"))
        self.btn_open_file.setText(_translate("MainWindow", "Open file"))
        self.label.setText(_translate("MainWindow", "Original image:"))
        self.label_3.setText(_translate("MainWindow", "Candidates for training:"))
        self.btn_candidates_generate.setText(_translate("MainWindow", "Generate candidates"))
        self.label_2.setText(_translate("MainWindow", "Max brightness variation:"))
        self.label_4.setText(_translate("MainWindow", "Max pixel shift:"))
        self.label_5.setText(_translate("MainWindow", "Max rotation:"))
        self.label_6.setText(_translate("MainWindow", "Max brightness noise:"))
        self.label_7.setText(_translate("MainWindow", "Candidates N:"))
        self.label_8.setText(_translate("MainWindow", "File base name:"))

