# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_3_CNN.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1058, 838)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_load_images = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load_images.setGeometry(QtCore.QRect(390, 70, 121, 31))
        self.btn_load_images.setObjectName("btn_load_images")
        self.btn_start_training = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_training.setGeometry(QtCore.QRect(530, 50, 131, 31))
        self.btn_start_training.setObjectName("btn_start_training")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 80, 101, 21))
        self.label_3.setObjectName("label_3")
        self.spin_iterations = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_iterations.setGeometry(QtCore.QRect(740, 50, 51, 31))
        self.spin_iterations.setMinimum(0)
        self.spin_iterations.setMaximum(1000)
        self.spin_iterations.setProperty("value", 20)
        self.spin_iterations.setObjectName("spin_iterations")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(670, 60, 71, 16))
        self.label_5.setObjectName("label_5")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(800, 50, 231, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.ocl_test_image = QtWidgets.QLabel(self.centralwidget)
        self.ocl_test_image.setGeometry(QtCore.QRect(780, 80, 128, 128))
        self.ocl_test_image.setText("")
        self.ocl_test_image.setObjectName("ocl_test_image")
        self.spin_test_array_id = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_test_array_id.setGeometry(QtCore.QRect(670, 150, 42, 31))
        self.spin_test_array_id.setMinimum(0)
        self.spin_test_array_id.setMaximum(3)
        self.spin_test_array_id.setProperty("value", 0)
        self.spin_test_array_id.setObjectName("spin_test_array_id")
        self.btn_predict = QtWidgets.QPushButton(self.centralwidget)
        self.btn_predict.setGeometry(QtCore.QRect(530, 150, 131, 31))
        self.btn_predict.setObjectName("btn_predict")
        self.label_predicted = QtWidgets.QLabel(self.centralwidget)
        self.label_predicted.setGeometry(QtCore.QRect(520, 190, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_predicted.setFont(font)
        self.label_predicted.setAlignment(QtCore.Qt.AlignCenter)
        self.label_predicted.setObjectName("label_predicted")
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setGeometry(QtCore.QRect(920, 80, 16, 111))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_3.setGeometry(QtCore.QRect(950, 80, 16, 111))
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_4 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_4.setGeometry(QtCore.QRect(980, 80, 16, 111))
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_4.setObjectName("progressBar_4")
        self.progressBar_5 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_5.setGeometry(QtCore.QRect(1010, 80, 16, 111))
        self.progressBar_5.setProperty("value", 0)
        self.progressBar_5.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_5.setObjectName("progressBar_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(920, 190, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 110, 500, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(950, 190, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(980, 190, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1010, 190, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.btn_save_to_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_to_file.setGeometry(QtCore.QRect(530, 110, 131, 31))
        self.btn_save_to_file.setObjectName("btn_save_to_file")
        self.btn_load_from_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load_from_file.setGeometry(QtCore.QRect(530, 80, 131, 31))
        self.btn_load_from_file.setObjectName("btn_load_from_file")
        self.spin_images_n = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_images_n.setGeometry(QtCore.QRect(340, 70, 41, 31))
        self.spin_images_n.setMaximum(255)
        self.spin_images_n.setProperty("value", 50)
        self.spin_images_n.setObjectName("spin_images_n")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(320, 80, 21, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 120, 351, 16))
        self.label_11.setObjectName("label_11")
        self.btn_filter_1_generate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_filter_1_generate.setGeometry(QtCore.QRect(10, 140, 91, 31))
        self.btn_filter_1_generate.setObjectName("btn_filter_1_generate")
        self.btn_filter_1_load = QtWidgets.QPushButton(self.centralwidget)
        self.btn_filter_1_load.setGeometry(QtCore.QRect(10, 170, 131, 31))
        self.btn_filter_1_load.setObjectName("btn_filter_1_load")
        self.btn_filter_1_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_filter_1_save.setGeometry(QtCore.QRect(10, 200, 131, 31))
        self.btn_filter_1_save.setObjectName("btn_filter_1_save")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 191, 61))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.line_folder = QtWidgets.QLineEdit(self.groupBox)
        self.line_folder.setGeometry(QtCore.QRect(10, 30, 171, 21))
        self.line_folder.setObjectName("line_folder")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(160, 140, 321, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cvl_filter_1_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cvl_filter_1_1.setMinimumSize(QtCore.QSize(60, 60))
        self.cvl_filter_1_1.setMaximumSize(QtCore.QSize(60, 60))
        self.cvl_filter_1_1.setText("")
        self.cvl_filter_1_1.setObjectName("cvl_filter_1_1")
        self.gridLayout.addWidget(self.cvl_filter_1_1, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.cvl_filter_1_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cvl_filter_1_3.setMinimumSize(QtCore.QSize(60, 60))
        self.cvl_filter_1_3.setMaximumSize(QtCore.QSize(60, 60))
        self.cvl_filter_1_3.setText("")
        self.cvl_filter_1_3.setObjectName("cvl_filter_1_3")
        self.gridLayout.addWidget(self.cvl_filter_1_3, 1, 2, 1, 1)
        self.cvl_filter_1_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cvl_filter_1_2.setMinimumSize(QtCore.QSize(60, 60))
        self.cvl_filter_1_2.setMaximumSize(QtCore.QSize(60, 60))
        self.cvl_filter_1_2.setText("")
        self.cvl_filter_1_2.setObjectName("cvl_filter_1_2")
        self.gridLayout.addWidget(self.cvl_filter_1_2, 1, 1, 1, 1)
        self.cvl_filter_1_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cvl_filter_1_4.setMinimumSize(QtCore.QSize(60, 60))
        self.cvl_filter_1_4.setMaximumSize(QtCore.QSize(60, 60))
        self.cvl_filter_1_4.setText("")
        self.cvl_filter_1_4.setObjectName("cvl_filter_1_4")
        self.gridLayout.addWidget(self.cvl_filter_1_4, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 380, 500, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 390, 81, 16))
        self.label_15.setObjectName("label_15")
        self.btn_apply_filters = QtWidgets.QPushButton(self.centralwidget)
        self.btn_apply_filters.setGeometry(QtCore.QRect(10, 410, 91, 31))
        self.btn_apply_filters.setObjectName("btn_apply_filters")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(200, 400, 288, 122))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ocl_preview_src = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ocl_preview_src.setMinimumSize(QtCore.QSize(120, 120))
        self.ocl_preview_src.setMaximumSize(QtCore.QSize(120, 120))
        self.ocl_preview_src.setText("")
        self.ocl_preview_src.setObjectName("ocl_preview_src")
        self.horizontalLayout.addWidget(self.ocl_preview_src)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.ocl_preview_filter = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ocl_preview_filter.setMinimumSize(QtCore.QSize(30, 30))
        self.ocl_preview_filter.setMaximumSize(QtCore.QSize(30, 30))
        self.ocl_preview_filter.setText("")
        self.ocl_preview_filter.setObjectName("ocl_preview_filter")
        self.horizontalLayout.addWidget(self.ocl_preview_filter)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        self.ocl_preview_result = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ocl_preview_result.setMinimumSize(QtCore.QSize(96, 96))
        self.ocl_preview_result.setMaximumSize(QtCore.QSize(96, 96))
        self.ocl_preview_result.setText("")
        self.ocl_preview_result.setObjectName("ocl_preview_result")
        self.horizontalLayout.addWidget(self.ocl_preview_result)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(10, 540, 101, 21))
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.spin_preview_from = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_preview_from.setGeometry(QtCore.QRect(120, 530, 41, 31))
        self.spin_preview_from.setMinimum(0)
        self.spin_preview_from.setMaximum(3)
        self.spin_preview_from.setProperty("value", 0)
        self.spin_preview_from.setObjectName("spin_preview_from")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(30, 570, 81, 21))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.spin_preview_n = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_preview_n.setGeometry(QtCore.QRect(120, 560, 41, 31))
        self.spin_preview_n.setMinimum(0)
        self.spin_preview_n.setMaximum(256)
        self.spin_preview_n.setProperty("value", 0)
        self.spin_preview_n.setObjectName("spin_preview_n")
        self.btn_preview_filters = QtWidgets.QPushButton(self.centralwidget)
        self.btn_preview_filters.setGeometry(QtCore.QRect(100, 600, 91, 31))
        self.btn_preview_filters.setObjectName("btn_preview_filters")
        self.btn_filter_2_generate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_filter_2_generate.setGeometry(QtCore.QRect(10, 270, 91, 31))
        self.btn_filter_2_generate.setObjectName("btn_filter_2_generate")
        self.btn_filter_2_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_filter_2_save.setGeometry(QtCore.QRect(10, 330, 131, 31))
        self.btn_filter_2_save.setObjectName("btn_filter_2_save")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(10, 250, 351, 16))
        self.label_20.setObjectName("label_20")
        self.btn_filter_2_load = QtWidgets.QPushButton(self.centralwidget)
        self.btn_filter_2_load.setGeometry(QtCore.QRect(10, 300, 131, 31))
        self.btn_filter_2_load.setObjectName("btn_filter_2_load")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(160, 270, 321, 91))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cvl_filter_2_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cvl_filter_2_1.setMinimumSize(QtCore.QSize(60, 60))
        self.cvl_filter_2_1.setMaximumSize(QtCore.QSize(60, 60))
        self.cvl_filter_2_1.setText("")
        self.cvl_filter_2_1.setObjectName("cvl_filter_2_1")
        self.gridLayout_2.addWidget(self.cvl_filter_2_1, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 0, 0, 1, 1)
        self.cvl_filter_2_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cvl_filter_2_3.setMinimumSize(QtCore.QSize(60, 60))
        self.cvl_filter_2_3.setMaximumSize(QtCore.QSize(60, 60))
        self.cvl_filter_2_3.setText("")
        self.cvl_filter_2_3.setObjectName("cvl_filter_2_3")
        self.gridLayout_2.addWidget(self.cvl_filter_2_3, 1, 2, 1, 1)
        self.cvl_filter_2_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cvl_filter_2_2.setMinimumSize(QtCore.QSize(60, 60))
        self.cvl_filter_2_2.setMaximumSize(QtCore.QSize(60, 60))
        self.cvl_filter_2_2.setText("")
        self.cvl_filter_2_2.setObjectName("cvl_filter_2_2")
        self.gridLayout_2.addWidget(self.cvl_filter_2_2, 1, 1, 1, 1)
        self.cvl_filter_2_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cvl_filter_2_4.setMinimumSize(QtCore.QSize(60, 60))
        self.cvl_filter_2_4.setMaximumSize(QtCore.QSize(60, 60))
        self.cvl_filter_2_4.setText("")
        self.cvl_filter_2_4.setObjectName("cvl_filter_2_4")
        self.gridLayout_2.addWidget(self.cvl_filter_2_4, 1, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 3, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 240, 500, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(230, 530, 201, 122))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ocl_preview_src_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.ocl_preview_src_2.setMinimumSize(QtCore.QSize(96, 96))
        self.ocl_preview_src_2.setMaximumSize(QtCore.QSize(96, 96))
        self.ocl_preview_src_2.setText("")
        self.ocl_preview_src_2.setObjectName("ocl_preview_src_2")
        self.horizontalLayout_2.addWidget(self.ocl_preview_src_2)
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_2.addWidget(self.label_25)
        self.ocl_preview_filter_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.ocl_preview_filter_2.setMinimumSize(QtCore.QSize(12, 12))
        self.ocl_preview_filter_2.setMaximumSize(QtCore.QSize(12, 12))
        self.ocl_preview_filter_2.setText("")
        self.ocl_preview_filter_2.setObjectName("ocl_preview_filter_2")
        self.horizontalLayout_2.addWidget(self.ocl_preview_filter_2)
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_2.addWidget(self.label_26)
        self.ocl_preview_result_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.ocl_preview_result_2.setMinimumSize(QtCore.QSize(48, 48))
        self.ocl_preview_result_2.setMaximumSize(QtCore.QSize(48, 48))
        self.ocl_preview_result_2.setText("")
        self.ocl_preview_result_2.setObjectName("ocl_preview_result_2")
        self.horizontalLayout_2.addWidget(self.ocl_preview_result_2)
        self.btn_filters_load = QtWidgets.QPushButton(self.centralwidget)
        self.btn_filters_load.setGeometry(QtCore.QRect(10, 440, 131, 31))
        self.btn_filters_load.setObjectName("btn_filters_load")
        self.btn_filters_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_filters_save.setGeometry(QtCore.QRect(10, 470, 131, 31))
        self.btn_filters_save.setObjectName("btn_filters_save")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 30, 47, 13))
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(530, 250, 514, 539))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_2.addWidget(self.label_27)
        self.ocl_preview_cnn = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ocl_preview_cnn.setMinimumSize(QtCore.QSize(512, 512))
        self.ocl_preview_cnn.setMaximumSize(QtCore.QSize(512, 512))
        self.ocl_preview_cnn.setText("")
        self.ocl_preview_cnn.setObjectName("ocl_preview_cnn")
        self.verticalLayout_2.addWidget(self.ocl_preview_cnn)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(510, 110, 3, 680))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LR3 CNN"))
        self.btn_load_images.setText(_translate("MainWindow", "Load images"))
        self.btn_start_training.setText(_translate("MainWindow", "Train"))
        self.label.setText(_translate("MainWindow", "FCNN - Fucking Convolutional Neural Network"))
        self.label_3.setText(_translate("MainWindow", "{0 - 3}_{N}.bmp"))
        self.label_5.setText(_translate("MainWindow", "Iterations: "))
        self.btn_predict.setText(_translate("MainWindow", "Predict"))
        self.label_predicted.setText(_translate("MainWindow", "EMPTY"))
        self.label_6.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "2"))
        self.label_8.setText(_translate("MainWindow", "3"))
        self.label_9.setText(_translate("MainWindow", "4"))
        self.btn_save_to_file.setText(_translate("MainWindow", "Save to file"))
        self.btn_load_from_file.setText(_translate("MainWindow", "Load from file"))
        self.label_10.setText(_translate("MainWindow", "N:"))
        self.label_11.setText(_translate("MainWindow", "1. Convolutional filters: (Black = 0, White = 1)"))
        self.btn_filter_1_generate.setText(_translate("MainWindow", "Generate"))
        self.btn_filter_1_load.setText(_translate("MainWindow", "Load from File"))
        self.btn_filter_1_save.setText(_translate("MainWindow", "Save to File"))
        self.groupBox.setTitle(_translate("MainWindow", "Files folder"))
        self.line_folder.setText(_translate("MainWindow", "LR3_data/"))
        self.label_2.setText(_translate("MainWindow", "Filter 1"))
        self.label_12.setText(_translate("MainWindow", "Filter 2"))
        self.label_13.setText(_translate("MainWindow", "Filter 3"))
        self.label_14.setText(_translate("MainWindow", "Filter 4"))
        self.label_15.setText(_translate("MainWindow", "Apply filters:"))
        self.btn_apply_filters.setText(_translate("MainWindow", "Apply"))
        self.label_16.setText(_translate("MainWindow", "*"))
        self.label_17.setText(_translate("MainWindow", "="))
        self.label_18.setText(_translate("MainWindow", "Preview image:"))
        self.label_19.setText(_translate("MainWindow", "Image N:"))
        self.btn_preview_filters.setText(_translate("MainWindow", "Preview"))
        self.btn_filter_2_generate.setText(_translate("MainWindow", "Generate"))
        self.btn_filter_2_save.setText(_translate("MainWindow", "Save to File"))
        self.label_20.setText(_translate("MainWindow", "2. Pooling filters: (Black = 0, White = 1)"))
        self.btn_filter_2_load.setText(_translate("MainWindow", "Load from File"))
        self.label_21.setText(_translate("MainWindow", "Filter 1"))
        self.label_22.setText(_translate("MainWindow", "Filter 2"))
        self.label_23.setText(_translate("MainWindow", "Filter 3"))
        self.label_24.setText(_translate("MainWindow", "Filter 4"))
        self.label_25.setText(_translate("MainWindow", "*"))
        self.label_26.setText(_translate("MainWindow", "="))
        self.btn_filters_load.setText(_translate("MainWindow", "Load from File"))
        self.btn_filters_save.setText(_translate("MainWindow", "Save to File"))
        self.label_4.setText(_translate("MainWindow", "MLP:"))
        self.label_27.setText(_translate("MainWindow", "MLP Preview:"))

